// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fees/v1/events.proto

package feesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeeApplied captures telemetry for a fee assessment.
type FeeApplied struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Payer             []byte                 `protobuf:"bytes,1,opt,name=payer,proto3" json:"payer,omitempty"`
	Domain            string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	GrossWei          string                 `protobuf:"bytes,3,opt,name=gross_wei,json=grossWei,proto3" json:"gross_wei,omitempty"`
	FeeWei            string                 `protobuf:"bytes,4,opt,name=fee_wei,json=feeWei,proto3" json:"fee_wei,omitempty"`
	NetWei            string                 `protobuf:"bytes,5,opt,name=net_wei,json=netWei,proto3" json:"net_wei,omitempty"`
	PolicyVersion     uint64                 `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	OwnerWallet       []byte                 `protobuf:"bytes,7,opt,name=owner_wallet,json=ownerWallet,proto3" json:"owner_wallet,omitempty"`
	FreeTierApplied   bool                   `protobuf:"varint,8,opt,name=free_tier_applied,json=freeTierApplied,proto3" json:"free_tier_applied,omitempty"`
	FreeTierLimit     uint64                 `protobuf:"varint,9,opt,name=free_tier_limit,json=freeTierLimit,proto3" json:"free_tier_limit,omitempty"`
	FreeTierRemaining uint64                 `protobuf:"varint,10,opt,name=free_tier_remaining,json=freeTierRemaining,proto3" json:"free_tier_remaining,omitempty"`
	UsageCount        uint64                 `protobuf:"varint,11,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	WindowStartUnix   int64                  `protobuf:"varint,12,opt,name=window_start_unix,json=windowStartUnix,proto3" json:"window_start_unix,omitempty"`
	FeeBps            uint32                 `protobuf:"varint,13,opt,name=fee_bps,json=feeBps,proto3" json:"fee_bps,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FeeApplied) Reset() {
	*x = FeeApplied{}
	mi := &file_fees_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeApplied) ProtoMessage() {}

func (x *FeeApplied) ProtoReflect() protoreflect.Message {
	mi := &file_fees_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeApplied.ProtoReflect.Descriptor instead.
func (*FeeApplied) Descriptor() ([]byte, []int) {
	return file_fees_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *FeeApplied) GetPayer() []byte {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *FeeApplied) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *FeeApplied) GetGrossWei() string {
	if x != nil {
		return x.GrossWei
	}
	return ""
}

func (x *FeeApplied) GetFeeWei() string {
	if x != nil {
		return x.FeeWei
	}
	return ""
}

func (x *FeeApplied) GetNetWei() string {
	if x != nil {
		return x.NetWei
	}
	return ""
}

func (x *FeeApplied) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *FeeApplied) GetOwnerWallet() []byte {
	if x != nil {
		return x.OwnerWallet
	}
	return nil
}

func (x *FeeApplied) GetFreeTierApplied() bool {
	if x != nil {
		return x.FreeTierApplied
	}
	return false
}

func (x *FeeApplied) GetFreeTierLimit() uint64 {
	if x != nil {
		return x.FreeTierLimit
	}
	return 0
}

func (x *FeeApplied) GetFreeTierRemaining() uint64 {
	if x != nil {
		return x.FreeTierRemaining
	}
	return 0
}

func (x *FeeApplied) GetUsageCount() uint64 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *FeeApplied) GetWindowStartUnix() int64 {
	if x != nil {
		return x.WindowStartUnix
	}
	return 0
}

func (x *FeeApplied) GetFeeBps() uint32 {
	if x != nil {
		return x.FeeBps
	}
	return 0
}

var File_fees_v1_events_proto protoreflect.FileDescriptor

const file_fees_v1_events_proto_rawDesc = "\n\x92\x04\n\x1aproto/fees/v1/events.proto\x12\vnhb.fees.v1\"\xbd\x03\n\nFeeApplied\x12\x14\n\x05payer\x18\x01 \x01(\fR\x05payer\x12\x16\n\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1b\n\tgross_wei\x18\x03 \x01(\tR\bgrossWei\x12\x17\n\afee_wei\x18\x04 \x01(\tR\x06feeWei\x12\x17\n\anet_wei\x18\x05 \x01(\tR\x06netWei\x12%\n\x0epolicy_version\x18\x06 \x01(\x04R\rpolicyVersion\x12!\n\fowner_wallet\x18\a \x01(\fR\vownerWallet\x12*\n\x11free_tier_applied\x18\b \x01(\bR\x0ffreeTierApplied\x12&\n\x0ffree_tier_limit\x18\t \x01(\x04R\rfreeTierLimit\x12.\n\x13free_tier_remaining\x18\n \x01(\x04R\x11freeTierRemaining\x12\x1f\n\vusage_count\x18\v \x01(\x04R\nusageCount\x12*\n\x11window_start_unix\x18\f \x01(\x03R\x0fwindowStartUnix\x12\x17\n\afee_bps\x18\r \x01(\rR\x06feeBpsB\x1fZ\x1dnhbchain/proto/fees/v1;feesv1b\x06proto3"

var (
	file_fees_v1_events_proto_rawDescOnce sync.Once
	file_fees_v1_events_proto_rawDescData []byte
)

func file_fees_v1_events_proto_rawDescGZIP() []byte {
	file_fees_v1_events_proto_rawDescOnce.Do(func() {
		file_fees_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fees_v1_events_proto_rawDesc), len(file_fees_v1_events_proto_rawDesc)))
	})
	return file_fees_v1_events_proto_rawDescData
}

var file_fees_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fees_v1_events_proto_goTypes = []any{
	(*FeeApplied)(nil), // 0: nhb.fees.v1.FeeApplied
}
var file_fees_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fees_v1_events_proto_init() }
func file_fees_v1_events_proto_init() {
	if File_fees_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fees_v1_events_proto_rawDesc), len(file_fees_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fees_v1_events_proto_goTypes,
		DependencyIndexes: file_fees_v1_events_proto_depIdxs,
		MessageInfos:      file_fees_v1_events_proto_msgTypes,
	}.Build()
	File_fees_v1_events_proto = out.File
	file_fees_v1_events_proto_goTypes = nil
	file_fees_v1_events_proto_depIdxs = nil
}
