listen: ":50061"
consensus: "localhost:9090"
chain_id: "localnet"
signer_key: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
nonce_start: 1
fee:
  amount: ""
  denom: ""
  payer: ""
tls:
  cert: "services/governd/config/server.crt"
  key: "services/governd/config/server.key"
  client_ca: ""
auth:
  api_tokens: []
  mtls:
    allowed_common_names: []
consensus_client:
  allow_insecure: true
  tls:
    cert: ""
    key: ""
    ca: ""
  shared_secret:
    header: "authorization"
    token: ""
