// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pos/realtime.proto

package posv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Realtime_SubscribeFinality_FullMethodName = "/pos.v1.Realtime/SubscribeFinality"
)

// RealtimeClient is the client API for Realtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealtimeClient interface {
	SubscribeFinality(ctx context.Context, in *SubscribeFinalityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeFinalityResponse], error)
}

type realtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeClient(cc grpc.ClientConnInterface) RealtimeClient {
	return &realtimeClient{cc}
}

func (c *realtimeClient) SubscribeFinality(ctx context.Context, in *SubscribeFinalityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeFinalityResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Realtime_ServiceDesc.Streams[0], Realtime_SubscribeFinality_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeFinalityRequest, SubscribeFinalityResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Realtime_SubscribeFinalityClient = grpc.ServerStreamingClient[SubscribeFinalityResponse]

// RealtimeServer is the server API for Realtime service.
// All implementations must embed UnimplementedRealtimeServer
// for forward compatibility.
type RealtimeServer interface {
	SubscribeFinality(*SubscribeFinalityRequest, grpc.ServerStreamingServer[SubscribeFinalityResponse]) error
	mustEmbedUnimplementedRealtimeServer()
}

// UnimplementedRealtimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeServer struct{}

func (UnimplementedRealtimeServer) SubscribeFinality(*SubscribeFinalityRequest, grpc.ServerStreamingServer[SubscribeFinalityResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeFinality not implemented")
}
func (UnimplementedRealtimeServer) mustEmbedUnimplementedRealtimeServer() {}
func (UnimplementedRealtimeServer) testEmbeddedByValue()                  {}

// UnsafeRealtimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeServer will
// result in compilation errors.
type UnsafeRealtimeServer interface {
	mustEmbedUnimplementedRealtimeServer()
}

func RegisterRealtimeServer(s grpc.ServiceRegistrar, srv RealtimeServer) {
	// If the following call pancis, it indicates UnimplementedRealtimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Realtime_ServiceDesc, srv)
}

func _Realtime_SubscribeFinality_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeFinalityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeServer).SubscribeFinality(m, &grpc.GenericServerStream[SubscribeFinalityRequest, SubscribeFinalityResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Realtime_SubscribeFinalityServer = grpc.ServerStreamingServer[SubscribeFinalityResponse]

// Realtime_ServiceDesc is the grpc.ServiceDesc for Realtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Realtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pos.v1.Realtime",
	HandlerType: (*RealtimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeFinality",
			Handler:       _Realtime_SubscribeFinality_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pos/realtime.proto",
}
