// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pos/registry.proto

package posv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Merchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Paused        bool                   `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_pos_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Merchant) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MerchantAddr  string                 `protobuf:"bytes,2,opt,name=merchant_addr,json=merchantAddr,proto3" json:"merchant_addr,omitempty"`
	Revoked       bool                   `protobuf:"varint,3,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_pos_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetMerchantAddr() string {
	if x != nil {
		return x.MerchantAddr
	}
	return ""
}

func (x *Device) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type MsgRegisterMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MerchantAddr  string                 `protobuf:"bytes,2,opt,name=merchant_addr,json=merchantAddr,proto3" json:"merchant_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterMerchant) Reset() {
	*x = MsgRegisterMerchant{}
	mi := &file_pos_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterMerchant) ProtoMessage() {}

func (x *MsgRegisterMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterMerchant.ProtoReflect.Descriptor instead.
func (*MsgRegisterMerchant) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{2}
}

func (x *MsgRegisterMerchant) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgRegisterMerchant) GetMerchantAddr() string {
	if x != nil {
		return x.MerchantAddr
	}
	return ""
}

type MsgRegisterMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterMerchantResponse) Reset() {
	*x = MsgRegisterMerchantResponse{}
	mi := &file_pos_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterMerchantResponse) ProtoMessage() {}

func (x *MsgRegisterMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterMerchantResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterMerchantResponse) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{3}
}

func (x *MsgRegisterMerchantResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type MsgRegisterDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MerchantAddr  string                 `protobuf:"bytes,2,opt,name=merchant_addr,json=merchantAddr,proto3" json:"merchant_addr,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterDevice) Reset() {
	*x = MsgRegisterDevice{}
	mi := &file_pos_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterDevice) ProtoMessage() {}

func (x *MsgRegisterDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterDevice.ProtoReflect.Descriptor instead.
func (*MsgRegisterDevice) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{4}
}

func (x *MsgRegisterDevice) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgRegisterDevice) GetMerchantAddr() string {
	if x != nil {
		return x.MerchantAddr
	}
	return ""
}

func (x *MsgRegisterDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type MsgRegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterDeviceResponse) Reset() {
	*x = MsgRegisterDeviceResponse{}
	mi := &file_pos_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterDeviceResponse) ProtoMessage() {}

func (x *MsgRegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{5}
}

func (x *MsgRegisterDeviceResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type MsgPauseMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MerchantAddr  string                 `protobuf:"bytes,2,opt,name=merchant_addr,json=merchantAddr,proto3" json:"merchant_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPauseMerchant) Reset() {
	*x = MsgPauseMerchant{}
	mi := &file_pos_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPauseMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPauseMerchant) ProtoMessage() {}

func (x *MsgPauseMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPauseMerchant.ProtoReflect.Descriptor instead.
func (*MsgPauseMerchant) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{6}
}

func (x *MsgPauseMerchant) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgPauseMerchant) GetMerchantAddr() string {
	if x != nil {
		return x.MerchantAddr
	}
	return ""
}

type MsgPauseMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPauseMerchantResponse) Reset() {
	*x = MsgPauseMerchantResponse{}
	mi := &file_pos_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPauseMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPauseMerchantResponse) ProtoMessage() {}

func (x *MsgPauseMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPauseMerchantResponse.ProtoReflect.Descriptor instead.
func (*MsgPauseMerchantResponse) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{7}
}

func (x *MsgPauseMerchantResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type MsgResumeMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MerchantAddr  string                 `protobuf:"bytes,2,opt,name=merchant_addr,json=merchantAddr,proto3" json:"merchant_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgResumeMerchant) Reset() {
	*x = MsgResumeMerchant{}
	mi := &file_pos_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResumeMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResumeMerchant) ProtoMessage() {}

func (x *MsgResumeMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResumeMerchant.ProtoReflect.Descriptor instead.
func (*MsgResumeMerchant) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{8}
}

func (x *MsgResumeMerchant) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgResumeMerchant) GetMerchantAddr() string {
	if x != nil {
		return x.MerchantAddr
	}
	return ""
}

type MsgResumeMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgResumeMerchantResponse) Reset() {
	*x = MsgResumeMerchantResponse{}
	mi := &file_pos_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResumeMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResumeMerchantResponse) ProtoMessage() {}

func (x *MsgResumeMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResumeMerchantResponse.ProtoReflect.Descriptor instead.
func (*MsgResumeMerchantResponse) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{9}
}

func (x *MsgResumeMerchantResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type MsgRevokeDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MerchantAddr  string                 `protobuf:"bytes,2,opt,name=merchant_addr,json=merchantAddr,proto3" json:"merchant_addr,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevokeDevice) Reset() {
	*x = MsgRevokeDevice{}
	mi := &file_pos_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevokeDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevokeDevice) ProtoMessage() {}

func (x *MsgRevokeDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevokeDevice.ProtoReflect.Descriptor instead.
func (*MsgRevokeDevice) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{10}
}

func (x *MsgRevokeDevice) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgRevokeDevice) GetMerchantAddr() string {
	if x != nil {
		return x.MerchantAddr
	}
	return ""
}

func (x *MsgRevokeDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type MsgRevokeDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevokeDeviceResponse) Reset() {
	*x = MsgRevokeDeviceResponse{}
	mi := &file_pos_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevokeDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevokeDeviceResponse) ProtoMessage() {}

func (x *MsgRevokeDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevokeDeviceResponse.ProtoReflect.Descriptor instead.
func (*MsgRevokeDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{11}
}

func (x *MsgRevokeDeviceResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type MsgRestoreDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MerchantAddr  string                 `protobuf:"bytes,2,opt,name=merchant_addr,json=merchantAddr,proto3" json:"merchant_addr,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRestoreDevice) Reset() {
	*x = MsgRestoreDevice{}
	mi := &file_pos_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRestoreDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRestoreDevice) ProtoMessage() {}

func (x *MsgRestoreDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRestoreDevice.ProtoReflect.Descriptor instead.
func (*MsgRestoreDevice) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{12}
}

func (x *MsgRestoreDevice) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgRestoreDevice) GetMerchantAddr() string {
	if x != nil {
		return x.MerchantAddr
	}
	return ""
}

func (x *MsgRestoreDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type MsgRestoreDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRestoreDeviceResponse) Reset() {
	*x = MsgRestoreDeviceResponse{}
	mi := &file_pos_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRestoreDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRestoreDeviceResponse) ProtoMessage() {}

func (x *MsgRestoreDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRestoreDeviceResponse.ProtoReflect.Descriptor instead.
func (*MsgRestoreDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pos_registry_proto_rawDescGZIP(), []int{13}
}

func (x *MsgRestoreDeviceResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

var File_pos_registry_proto protoreflect.FileDescriptor

const file_pos_registry_proto_rawDesc = "" +
	"\n" +
	"\x12pos/registry.proto\x12\x06pos.v1\"<\n" +
	"\bMerchant\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\"d\n" +
	"\x06Device\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12#\n" +
	"\rmerchant_addr\x18\x02 \x01(\tR\fmerchantAddr\x12\x18\n" +
	"\arevoked\x18\x03 \x01(\bR\arevoked\"X\n" +
	"\x13MsgRegisterMerchant\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12#\n" +
	"\rmerchant_addr\x18\x02 \x01(\tR\fmerchantAddr\"6\n" +
	"\x1bMsgRegisterMerchantResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"s\n" +
	"\x11MsgRegisterDevice\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12#\n" +
	"\rmerchant_addr\x18\x02 \x01(\tR\fmerchantAddr\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"4\n" +
	"\x19MsgRegisterDeviceResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"U\n" +
	"\x10MsgPauseMerchant\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12#\n" +
	"\rmerchant_addr\x18\x02 \x01(\tR\fmerchantAddr\"3\n" +
	"\x18MsgPauseMerchantResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"V\n" +
	"\x11MsgResumeMerchant\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12#\n" +
	"\rmerchant_addr\x18\x02 \x01(\tR\fmerchantAddr\"4\n" +
	"\x19MsgResumeMerchantResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"q\n" +
	"\x0fMsgRevokeDevice\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12#\n" +
	"\rmerchant_addr\x18\x02 \x01(\tR\fmerchantAddr\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"2\n" +
	"\x17MsgRevokeDeviceResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"r\n" +
	"\x10MsgRestoreDevice\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12#\n" +
	"\rmerchant_addr\x18\x02 \x01(\tR\fmerchantAddr\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"3\n" +
	"\x18MsgRestoreDeviceResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash2\xe4\x03\n" +
	"\bRegistry\x12T\n" +
	"\x10RegisterMerchant\x12\x1b.pos.v1.MsgRegisterMerchant\x1a#.pos.v1.MsgRegisterMerchantResponse\x12N\n" +
	"\x0eRegisterDevice\x12\x19.pos.v1.MsgRegisterDevice\x1a!.pos.v1.MsgRegisterDeviceResponse\x12K\n" +
	"\rPauseMerchant\x12\x18.pos.v1.MsgPauseMerchant\x1a .pos.v1.MsgPauseMerchantResponse\x12N\n" +
	"\x0eResumeMerchant\x12\x19.pos.v1.MsgResumeMerchant\x1a!.pos.v1.MsgResumeMerchantResponse\x12H\n" +
	"\fRevokeDevice\x12\x17.pos.v1.MsgRevokeDevice\x1a\x1f.pos.v1.MsgRevokeDeviceResponse\x12K\n" +
	"\rRestoreDevice\x12\x18.pos.v1.MsgRestoreDevice\x1a .pos.v1.MsgRestoreDeviceResponseB\x1aZ\x18nhbchain/proto/pos;posv1b\x06proto3"

var (
	file_pos_registry_proto_rawDescOnce sync.Once
	file_pos_registry_proto_rawDescData []byte
)

func file_pos_registry_proto_rawDescGZIP() []byte {
	file_pos_registry_proto_rawDescOnce.Do(func() {
		file_pos_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pos_registry_proto_rawDesc), len(file_pos_registry_proto_rawDesc)))
	})
	return file_pos_registry_proto_rawDescData
}

var file_pos_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pos_registry_proto_goTypes = []any{
	(*Merchant)(nil),                    // 0: pos.v1.Merchant
	(*Device)(nil),                      // 1: pos.v1.Device
	(*MsgRegisterMerchant)(nil),         // 2: pos.v1.MsgRegisterMerchant
	(*MsgRegisterMerchantResponse)(nil), // 3: pos.v1.MsgRegisterMerchantResponse
	(*MsgRegisterDevice)(nil),           // 4: pos.v1.MsgRegisterDevice
	(*MsgRegisterDeviceResponse)(nil),   // 5: pos.v1.MsgRegisterDeviceResponse
	(*MsgPauseMerchant)(nil),            // 6: pos.v1.MsgPauseMerchant
	(*MsgPauseMerchantResponse)(nil),    // 7: pos.v1.MsgPauseMerchantResponse
	(*MsgResumeMerchant)(nil),           // 8: pos.v1.MsgResumeMerchant
	(*MsgResumeMerchantResponse)(nil),   // 9: pos.v1.MsgResumeMerchantResponse
	(*MsgRevokeDevice)(nil),             // 10: pos.v1.MsgRevokeDevice
	(*MsgRevokeDeviceResponse)(nil),     // 11: pos.v1.MsgRevokeDeviceResponse
	(*MsgRestoreDevice)(nil),            // 12: pos.v1.MsgRestoreDevice
	(*MsgRestoreDeviceResponse)(nil),    // 13: pos.v1.MsgRestoreDeviceResponse
}
var file_pos_registry_proto_depIdxs = []int32{
	2,  // 0: pos.v1.Registry.RegisterMerchant:input_type -> pos.v1.MsgRegisterMerchant
	4,  // 1: pos.v1.Registry.RegisterDevice:input_type -> pos.v1.MsgRegisterDevice
	6,  // 2: pos.v1.Registry.PauseMerchant:input_type -> pos.v1.MsgPauseMerchant
	8,  // 3: pos.v1.Registry.ResumeMerchant:input_type -> pos.v1.MsgResumeMerchant
	10, // 4: pos.v1.Registry.RevokeDevice:input_type -> pos.v1.MsgRevokeDevice
	12, // 5: pos.v1.Registry.RestoreDevice:input_type -> pos.v1.MsgRestoreDevice
	3,  // 6: pos.v1.Registry.RegisterMerchant:output_type -> pos.v1.MsgRegisterMerchantResponse
	5,  // 7: pos.v1.Registry.RegisterDevice:output_type -> pos.v1.MsgRegisterDeviceResponse
	7,  // 8: pos.v1.Registry.PauseMerchant:output_type -> pos.v1.MsgPauseMerchantResponse
	9,  // 9: pos.v1.Registry.ResumeMerchant:output_type -> pos.v1.MsgResumeMerchantResponse
	11, // 10: pos.v1.Registry.RevokeDevice:output_type -> pos.v1.MsgRevokeDeviceResponse
	13, // 11: pos.v1.Registry.RestoreDevice:output_type -> pos.v1.MsgRestoreDeviceResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pos_registry_proto_init() }
func file_pos_registry_proto_init() {
	if File_pos_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pos_registry_proto_rawDesc), len(file_pos_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pos_registry_proto_goTypes,
		DependencyIndexes: file_pos_registry_proto_depIdxs,
		MessageInfos:      file_pos_registry_proto_msgTypes,
	}.Build()
	File_pos_registry_proto = out.File
	file_pos_registry_proto_goTypes = nil
	file_pos_registry_proto_depIdxs = nil
}
