run:
  timeout: 5m
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - revive
    - misspell
    - unparam
    - gocyclo
    - prealloc
linters-settings:
  gocyclo:
    min-complexity: 15
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
