ListenAddress = "0.0.0.0:6002"
RPCAddress = "0.0.0.0:8081"
DataDir = "./nhb-data-local"
# Required: point to the genesis file that defines your local dev network.
GenesisFile = "./config/genesis.local.json"
# Set to true only if you intentionally want the node to fabricate an ephemeral genesis.
AllowAutogenesis = false
ValidatorKeystorePath = "./nhb-data-local/validator.keystore"
ValidatorKMSURI = ""
ValidatorKMSEnv = ""
NetworkName = "nhb-local"

[mempool]
MaxTransactions = 5000
[p2p]
NetworkId = 187001
MaxPeers = 64
MaxInbound = 60
MaxOutbound = 30
MinPeers = 12
OutboundPeers = 16
Bootnodes = []
PersistentPeers = []
Seeds = []
BanScore = 100
GreyScore = 50
RateMsgsPerSec = 50
Burst = 200
HandshakeTimeoutMs = 3000
PingIntervalSeconds = 30
PingTimeoutSeconds = 90
BanDurationSeconds = 3600
DialBackoffSeconds = 30
PEX = true

PeerBanSeconds = 3600
ReadTimeout = 90
WriteTimeout = 5
MaxMsgBytes = 1048576
ClientVersion = "nhbchain/node"
RPCAllowInsecure = true
# Treat container-style wildcard binds as loopback for local development.
RPCAllowInsecureUnspecified = true
RPCTLSCertFile = ""
RPCTLSKeyFile = ""
RPCTLSClientCAFile = ""

[global.pauses]
Staking = false

[network_security]
# Configure a shared secret for local development so consensusd only accepts
# authenticated requests. The daemon refuses to start when this block resolves
# to an empty secret. Production deployments should supply the secret via
# SharedSecretFile or SharedSecretEnv and/or enable mutual TLS.
SharedSecret = "local-dev-shared-secret"
# Local development defaults to plaintext. Keep this at true only for throwaway
# labs and always pair it with a shared secret. Production operators must
# provision TLS and set AllowInsecure = false; the daemon now fails fast when TLS
# material is absent.
AllowInsecure = true
# ServerTLSCertFile = "./tls/p2pd.crt"
# ServerTLSKeyFile = "./tls/p2pd.key"
# ClientTLSCertFile = "./tls/consensus.crt"
# ClientTLSKeyFile = "./tls/consensus.key"
