ListenAddress = ":6001"
RPCAddress = ":8080"
DataDir = "./nhb-data"
GenesisFile = ""
ValidatorKeystorePath = ""
ValidatorKMSURI = ""
ValidatorKMSEnv = ""
NetworkName = "nhb-local"
Bootnodes = []
PersistentPeers = []
