ListenAddress = ":6002"
RPCAddress = ":8081"
DataDir = "./nhb-data-peer"
GenesisFile = ""
ValidatorKeystorePath = "./validator-peer.keystore"
ValidatorKMSURI = ""
ValidatorKMSEnv = ""
NetworkName = "nhb-local"
Bootnodes = []
PersistentPeers = []
MaxPeers = 64
MaxInbound = 32
MaxOutbound = 32
PeerBanSeconds = 900
ReadTimeout = 90
WriteTimeout = 5
MaxMsgBytes = 1048576
MaxMsgsPerSecond = 32
ClientVersion = "nhbchain/node"
