ListenAddress = "127.0.0.1:6001"
# Production deployments are expected to front consensusd with a reverse proxy
# or load balancer that terminates TLS on the public interface. Bind RPC to
# loopback so the daemon is only reachable through the proxy layer.
RPCAddress = "127.0.0.1:8080"
DataDir = "./nhb-data"
# Provide the absolute or relative path to the vetted genesis file for this network.
GenesisFile = "./config/genesis.json"
# DEV ONLY: override to true exclusively for ephemeral local testing.
AllowAutogenesis = false
ValidatorKeystorePath = ""
ValidatorKMSURI = ""
ValidatorKMSEnv = ""
NetworkName = "nhb-local"

[mempool]
MaxTransactions = 5000
[p2p]
NetworkId = 187001
MaxPeers = 64
MaxInbound = 60
MaxOutbound = 30
MinPeers = 12
OutboundPeers = 16
Bootnodes = []
PersistentPeers = []
Seeds = ["nhb1seed...@seed1.nhb:38766","nhb1seed...@seed2.nhb:38766"]
BanScore = 100
GreyScore = 50
RateMsgsPerSec = 50
Burst = 200
HandshakeTimeoutMs = 3000
PingIntervalSeconds = 30
PingTimeoutSeconds = 90
BanDurationSeconds = 3600
DialBackoffSeconds = 30
PEX = true

[network_security]
# Shared-secret token distributed out-of-band. Configure one of the following
# sources so consensusd and p2pd can authenticate each other. The daemon will
# refuse to start if none resolve to a non-empty value.
SharedSecretEnv = "NHB_NETWORK_SHARED_SECRET"
SharedSecretFile = "/etc/nhb/network.token"
SharedSecret = ""
# Production deployments must disable plaintext by leaving AllowInsecure=false
# and provisioning TLS certificates. The daemon will now fail fast when TLS is
# missing unless this flag is explicitly set to true. Local lab setups can flip
# it temporarily when TLS is not available, but must still provide a shared
# secret or client certificates.
AllowInsecure = false
AuthorizationHeader = "x-nhb-network-token"
AllowUnauthenticatedReads = false
ServerTLSCertFile = "/etc/nhb/tls/p2pd.crt"
ServerTLSKeyFile = "/etc/nhb/tls/p2pd.key"
ClientTLSCertFile = "/etc/nhb/tls/consensus.crt"
ClientTLSKeyFile = "/etc/nhb/tls/consensus.key"
ClientCAFile = "/etc/nhb/tls/consensus-ca.pem"
ServerCAFile = "/etc/nhb/tls/p2pd-ca.pem"
AllowedClientCommonNames = ["consensusd"]
ServerName = "p2pd.internal"


[global.staking]
MaxEmissionPerYearWei = "5000000000000000000"

PeerBanSeconds = 3600
ReadTimeout = 90
WriteTimeout = 5
MaxMsgBytes = 1048576
ClientVersion = "nhbchain/node"
RPCAllowInsecure = false
# RPCAllowInsecureUnspecified must remain false in production. When set to true
# alongside RPCAllowInsecure it treats unspecified listener binds (0.0.0.0) as
# loopback for tightly controlled lab environments such as container port-forwarding.
RPCAllowInsecureUnspecified = false
RPCTLSCertFile = "/etc/nhb/rpc/rpc.crt"
RPCTLSKeyFile = "/etc/nhb/rpc/rpc.key"
RPCTLSClientCAFile = "/etc/nhb/rpc/clients-ca.pem"
RPCAllowlistCIDRs = ["10.10.0.0/16", "192.168.0.0/24"]

[RPCProxyHeaders]
XForwardedFor = "ignore"
XRealIP = "ignore"

[RPCJWT]
Enable = true
Alg = "HS256"
HSSecretEnv = "NHB_RPC_JWT_SECRET"
Issuer = "nhb-rpc"
Audience = ["wallets"]
MaxSkewSeconds = 120

[global.pauses]
Staking = false

[global.fees]
free_tier_tx_per_month = 100
mdr_basis_points = 150
owner_wallet = "nhb1tctz3yvhrwztnp6ds3s48qp4jgfujcvhgxxpka"

[[global.fees.assets]]
asset = "NHB"
mdr_basis_points = 150
owner_wallet = "nhb1tctz3yvhrwztnp6ds3s48qp4jgfujcvhgxxpka"

[[global.fees.assets]]
asset = "ZNHB"
mdr_basis_points = 150
owner_wallet = "znhb19l75s7jkyzxp4z7lj3ddgn9r89y3kps54wpv0w"

[global.loyalty.Dynamic]
# Operators can override these defaults per environment while the guard remains enabled by default.
targetbps = 50
minbps = 25
maxbps = 100
smoothingstepbps = 5
coveragemax = 0.50
coveragelookbackdays = 7
dailycappctof7dfees = 0.60
dailycapusd = 5000
yearlycappctofinitialsupply = 10
enableprorate = true
EnforceProRate = true

  [global.loyalty.Dynamic.PriceGuard]
  enabled = true
  pricepair = "ZNHB/USD"
  twapwindowseconds = 7200
  maxdeviationbps = 300
  pricemaxageseconds = 600

[potso.rewards]
EpochLengthBlocks = 120
AlphaStakeBps = 7000
MinPayoutWei = "1000000000000000"
EmissionPerEpoch = "0"
TreasuryAddress = "nhb1exampletreasury000000000000000000000"
MaxWinnersPerEpoch = 5000
CarryRemainder = true
PayoutMode = "auto"

[potso.weights]
AlphaStakeBps = 7000
TxWeightBps = 6000
EscrowWeightBps = 3000
UptimeWeightBps = 1000
MaxEngagementPerEpoch = 1000
MinStakeToWinWei = "0"
MinEngagementToWin = 0
DecayHalfLifeEpochs = 7
TopKWinners = 5000
TieBreak = "addrHash"

[potso.abuse]
MinStakeToEarnWei = "0"
QuadraticTxDampenAfter = 0
QuadraticTxDampenPower = 2
MaxUserShareBps = 0

[governance]
MinDepositWei = "1000e18"
VotingPeriodSeconds = 604800
TimelockSeconds = 172800
QuorumBps = 2000
PassThresholdBps = 5000
AllowedParams = [
  "fees.baseFee",
  "staking.minimumValidatorStake",
  "staking.aprBps",
  "staking.payoutPeriodDays",
  "staking.unbondingDays",
  "staking.minStakeWei",
  "staking.maxEmissionPerYearWei",
  "staking.rewardAsset",
  "staking.compoundDefault",
  "loyalty.dynamic.targetBps",
  "loyalty.dynamic.minBps",
  "loyalty.dynamic.maxBps",
  "loyalty.dynamic.smoothingStepBps",
  "loyalty.dynamic.coverageMax",
  "loyalty.dynamic.coverageLookbackDays",
  "loyalty.dynamic.dailyCapPctOf7dFees",
  "loyalty.dynamic.dailyCapUsd",
  "loyalty.dynamic.yearlyCapPctOfInitialSupply",
  "loyalty.dynamic.priceGuard.pricePair",
  "loyalty.dynamic.priceGuard.twapWindowSeconds",
  "loyalty.dynamic.priceGuard.priceMaxAgeSeconds",
  "loyalty.dynamic.priceGuard.maxDeviationBps",
  "loyalty.dynamic.priceGuard.enabled",
  "network.seeds",
  "potso.abuse.MaxUserShareBps",
  "potso.abuse.MinStakeToEarnWei",
  "potso.abuse.QuadraticTxDampenAfter",
  "potso.abuse.QuadraticTxDampenPower",
  "potso.rewards.EmissionPerEpochWei",
  "potso.weights.AlphaStakeBps",
]
BlockTimestampToleranceSeconds = 5

[swap]
AllowedFiat = ["USD","EUR","GBP"]
MaxQuoteAgeSeconds = 120
SlippageBps = 50
OraclePriority = ["nowpayments","coingecko","manual"]
TwapWindowSeconds = 300
TwapSampleCap = 128
PayoutAuthorities = ["treasury"]

[swap.risk]
PerAddressDailyCapWei = "10000e18"
PerAddressMonthlyCapWei = "300000e18"
PerTxMinWei = "1e18"
PerTxMaxWei = "50000e18"
VelocityWindowSeconds = 600
VelocityMaxMints = 5
SanctionsCheckEnabled = true

[swap.providers]
Allow = ["nowpayments"]
