ListenAddress = ":6002"
RPCAddress = ":8081"
DataDir = "./nhb-data-peer"
GenesisFile = ""
ValidatorKeystorePath = "./validator-peer.keystore"
ValidatorKMSURI = ""
ValidatorKMSEnv = ""
NetworkName = "nhb-local"
[p2p]
NetworkId = 187001
MaxPeers = 64
MaxInbound = 60
MaxOutbound = 30
Bootnodes = []
PersistentPeers = []
BanScore = 100
GreyScore = 50
RateMsgsPerSec = 50
Burst = 200
HandshakeTimeoutMs = 5000

PeerBanSeconds = 900
ReadTimeout = 90
WriteTimeout = 5
MaxMsgBytes = 1048576
ClientVersion = "nhbchain/node"
