ListenAddress = ":6001"
RPCAddress = ":8080"
DataDir = "./nhb-data"
GenesisFile = ""
ValidatorKeystorePath = ""
ValidatorKMSURI = ""
ValidatorKMSEnv = ""
NetworkName = "nhb-local"
Bootnodes = []
PersistentPeers = []
MaxPeers = 64
MaxInbound = 32
MaxOutbound = 32
PeerBanSeconds = 900
ReadTimeout = 90
WriteTimeout = 5
MaxMsgBytes = 1048576
MaxMsgsPerSecond = 32
ClientVersion = "nhbchain/node"

[potso.rewards]
EpochLengthBlocks = 120
AlphaStakeBps = 7000
MinPayoutWei = "1000000000000000"
EmissionPerEpoch = "0"
TreasuryAddress = "nhb1exampletreasury000000000000000000000"
MaxWinnersPerEpoch = 5000
CarryRemainder = true
