ListenAddress = "0.0.0.0:6002"
RPCAddress = "0.0.0.0:8081"
DataDir = "./nhb-data-local"
GenesisFile = ""
ValidatorKeystorePath = "./validator-local.keystore"
ValidatorKMSURI = ""
ValidatorKMSEnv = ""
NetworkName = "nhb-local"
[p2p]
NetworkId = 187001
MaxPeers = 64
MaxInbound = 60
MaxOutbound = 30
Bootnodes = ["34.67.8.77:6001"]
PersistentPeers = []
BanScore = 100
GreyScore = 50
RateMsgsPerSec = 50
Burst = 200
HandshakeTimeoutMs = 5000

PeerBanSeconds = 900
ReadTimeout = 90
WriteTimeout = 5
MaxMsgBytes = 1048576
ClientVersion = "nhbchain/node"
