ListenAddress = ":6001"
RPCAddress = ":8080"
DataDir = "./nhb-data"
GenesisFile = ""
ValidatorKeystorePath = ""
ValidatorKMSURI = ""
ValidatorKMSEnv = ""
NetworkName = "nhb-local"
[p2p]
NetworkId = 187001
MaxPeers = 64
MaxInbound = 60
MaxOutbound = 30
Bootnodes = ["enode://..."]
PersistentPeers = []
BanScore = 100
GreyScore = 50
RateMsgsPerSec = 50
Burst = 200
HandshakeTimeoutMs = 5000

PeerBanSeconds = 900
ReadTimeout = 90
WriteTimeout = 5
MaxMsgBytes = 1048576
ClientVersion = "nhbchain/node"

[potso.rewards]
EpochLengthBlocks = 120
AlphaStakeBps = 7000
MinPayoutWei = "1000000000000000"
EmissionPerEpoch = "0"
TreasuryAddress = "nhb1exampletreasury000000000000000000000"
MaxWinnersPerEpoch = 5000
CarryRemainder = true
PayoutMode = "auto"

[potso.weights]
AlphaStakeBps = 7000
TxWeightBps = 6000
EscrowWeightBps = 3000
UptimeWeightBps = 1000
MaxEngagementPerEpoch = 1000
MinStakeToWinWei = "0"
MinEngagementToWin = 0
DecayHalfLifeEpochs = 7
TopKWinners = 5000
TieBreak = "addrHash"

[governance]
MinDepositWei = "1000e18"
VotingPeriodSeconds = 604800
TimelockSeconds = 172800
QuorumBps = 2000
PassThresholdBps = 5000
AllowedParams = ["potso.weights.AlphaStakeBps","potso.rewards.EmissionPerEpochWei","fees.baseFee"]
