global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: nhb-local
rule_files:
  - rules/slo.rules.yml
scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: nhb-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - gateway:9464
          - consensusd:9464
          - p2pd:9464
          - governd:9464
          - lendingd:9464
          - swapd:9464
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: job
        replacement: nhb-service
