// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: swap/v1/tx.proto

package swapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgSwapExactIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trader       string `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	PoolId       string `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	TokenIn      string `protobuf:"bytes,3,opt,name=token_in,json=tokenIn,proto3" json:"token_in,omitempty"`
	AmountIn     string `protobuf:"bytes,4,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	MinAmountOut string `protobuf:"bytes,5,opt,name=min_amount_out,json=minAmountOut,proto3" json:"min_amount_out,omitempty"`
	Recipient    string `protobuf:"bytes,6,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *MsgSwapExactIn) Reset() {
	*x = MsgSwapExactIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSwapExactIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSwapExactIn) ProtoMessage() {}

func (x *MsgSwapExactIn) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSwapExactIn.ProtoReflect.Descriptor instead.
func (*MsgSwapExactIn) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSwapExactIn) GetTrader() string {
	if x != nil {
		return x.Trader
	}
	return ""
}

func (x *MsgSwapExactIn) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *MsgSwapExactIn) GetTokenIn() string {
	if x != nil {
		return x.TokenIn
	}
	return ""
}

func (x *MsgSwapExactIn) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *MsgSwapExactIn) GetMinAmountOut() string {
	if x != nil {
		return x.MinAmountOut
	}
	return ""
}

func (x *MsgSwapExactIn) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

type MsgSwapExactOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trader      string `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	PoolId      string `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	TokenOut    string `protobuf:"bytes,3,opt,name=token_out,json=tokenOut,proto3" json:"token_out,omitempty"`
	AmountOut   string `protobuf:"bytes,4,opt,name=amount_out,json=amountOut,proto3" json:"amount_out,omitempty"`
	MaxAmountIn string `protobuf:"bytes,5,opt,name=max_amount_in,json=maxAmountIn,proto3" json:"max_amount_in,omitempty"`
	Recipient   string `protobuf:"bytes,6,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *MsgSwapExactOut) Reset() {
	*x = MsgSwapExactOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSwapExactOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSwapExactOut) ProtoMessage() {}

func (x *MsgSwapExactOut) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSwapExactOut.ProtoReflect.Descriptor instead.
func (*MsgSwapExactOut) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSwapExactOut) GetTrader() string {
	if x != nil {
		return x.Trader
	}
	return ""
}

func (x *MsgSwapExactOut) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *MsgSwapExactOut) GetTokenOut() string {
	if x != nil {
		return x.TokenOut
	}
	return ""
}

func (x *MsgSwapExactOut) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *MsgSwapExactOut) GetMaxAmountIn() string {
	if x != nil {
		return x.MaxAmountIn
	}
	return ""
}

func (x *MsgSwapExactOut) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

type MsgMintDepositVoucher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authority string          `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Voucher   *DepositVoucher `protobuf:"bytes,2,opt,name=voucher,proto3" json:"voucher,omitempty"`
}

func (x *MsgMintDepositVoucher) Reset() {
	*x = MsgMintDepositVoucher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMintDepositVoucher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintDepositVoucher) ProtoMessage() {}

func (x *MsgMintDepositVoucher) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintDepositVoucher.ProtoReflect.Descriptor instead.
func (*MsgMintDepositVoucher) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgMintDepositVoucher) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgMintDepositVoucher) GetVoucher() *DepositVoucher {
	if x != nil {
		return x.Voucher
	}
	return nil
}

type MsgMintDepositVoucherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgMintDepositVoucherResponse) Reset() {
	*x = MsgMintDepositVoucherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMintDepositVoucherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintDepositVoucherResponse) ProtoMessage() {}

func (x *MsgMintDepositVoucherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintDepositVoucherResponse.ProtoReflect.Descriptor instead.
func (*MsgMintDepositVoucherResponse) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgCreateCashOutIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Intent  *CashOutIntent `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
}

func (x *MsgCreateCashOutIntent) Reset() {
	*x = MsgCreateCashOutIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateCashOutIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateCashOutIntent) ProtoMessage() {}

func (x *MsgCreateCashOutIntent) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateCashOutIntent.ProtoReflect.Descriptor instead.
func (*MsgCreateCashOutIntent) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgCreateCashOutIntent) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MsgCreateCashOutIntent) GetIntent() *CashOutIntent {
	if x != nil {
		return x.Intent
	}
	return nil
}

type MsgCreateCashOutIntentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgCreateCashOutIntentResponse) Reset() {
	*x = MsgCreateCashOutIntentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateCashOutIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateCashOutIntentResponse) ProtoMessage() {}

func (x *MsgCreateCashOutIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateCashOutIntentResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateCashOutIntentResponse) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{5}
}

type MsgPayoutReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authority string         `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Receipt   *PayoutReceipt `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
}

func (x *MsgPayoutReceipt) Reset() {
	*x = MsgPayoutReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPayoutReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPayoutReceipt) ProtoMessage() {}

func (x *MsgPayoutReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPayoutReceipt.ProtoReflect.Descriptor instead.
func (*MsgPayoutReceipt) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgPayoutReceipt) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgPayoutReceipt) GetReceipt() *PayoutReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type MsgPayoutReceiptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPayoutReceiptResponse) Reset() {
	*x = MsgPayoutReceiptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPayoutReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPayoutReceiptResponse) ProtoMessage() {}

func (x *MsgPayoutReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPayoutReceiptResponse.ProtoReflect.Descriptor instead.
func (*MsgPayoutReceiptResponse) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{7}
}

type MsgAbortCashOutIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	IntentId  string `protobuf:"bytes,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	Reason    string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *MsgAbortCashOutIntent) Reset() {
	*x = MsgAbortCashOutIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAbortCashOutIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAbortCashOutIntent) ProtoMessage() {}

func (x *MsgAbortCashOutIntent) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAbortCashOutIntent.ProtoReflect.Descriptor instead.
func (*MsgAbortCashOutIntent) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgAbortCashOutIntent) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgAbortCashOutIntent) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *MsgAbortCashOutIntent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MsgAbortCashOutIntentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgAbortCashOutIntentResponse) Reset() {
	*x = MsgAbortCashOutIntentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_tx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAbortCashOutIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAbortCashOutIntentResponse) ProtoMessage() {}

func (x *MsgAbortCashOutIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_tx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAbortCashOutIntentResponse.ProtoReflect.Descriptor instead.
func (*MsgAbortCashOutIntentResponse) Descriptor() ([]byte, []int) {
	return file_swap_v1_tx_proto_rawDescGZIP(), []int{9}
}

var File_swap_v1_tx_proto protoreflect.FileDescriptor

var file_swap_v1_tx_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x1a, 0x14, 0x73, 0x77, 0x61,
	0x70, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbd, 0x01, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x53, 0x77, 0x61, 0x70, 0x45, 0x78, 0x61,
	0x63, 0x74, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x12, 0x24, 0x0a,
	0x0e, 0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6f, 0x75, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x4f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x22, 0xc0, 0x01, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x53, 0x77, 0x61, 0x70, 0x45, 0x78, 0x61,
	0x63, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x4f, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6f, 0x75,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4f,
	0x75, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x22, 0x68, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6e, 0x74, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x07, 0x76,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73,
	0x77, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x56, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x07, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x22, 0x1f,
	0x0a, 0x1d, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x62, 0x0a, 0x16, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x73, 0x68,
	0x4f, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x73, 0x68, 0x4f, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x69, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x1e, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x73, 0x68, 0x4f, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x62, 0x0a, 0x10, 0x4d, 0x73, 0x67, 0x50, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x30, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x4d, 0x73, 0x67,
	0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6a, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x43, 0x61, 0x73, 0x68, 0x4f, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x1f, 0x0a, 0x1d, 0x4d, 0x73, 0x67, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x43, 0x61, 0x73,
	0x68, 0x4f, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x6e, 0x68, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x77, 0x61,
	0x70, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_swap_v1_tx_proto_rawDescOnce sync.Once
	file_swap_v1_tx_proto_rawDescData = file_swap_v1_tx_proto_rawDesc
)

func file_swap_v1_tx_proto_rawDescGZIP() []byte {
	file_swap_v1_tx_proto_rawDescOnce.Do(func() {
		file_swap_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_swap_v1_tx_proto_rawDescData)
	})
	return file_swap_v1_tx_proto_rawDescData
}

var file_swap_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_swap_v1_tx_proto_goTypes = []interface{}{
	(*MsgSwapExactIn)(nil),                 // 0: swap.v1.MsgSwapExactIn
	(*MsgSwapExactOut)(nil),                // 1: swap.v1.MsgSwapExactOut
	(*MsgMintDepositVoucher)(nil),          // 2: swap.v1.MsgMintDepositVoucher
	(*MsgMintDepositVoucherResponse)(nil),  // 3: swap.v1.MsgMintDepositVoucherResponse
	(*MsgCreateCashOutIntent)(nil),         // 4: swap.v1.MsgCreateCashOutIntent
	(*MsgCreateCashOutIntentResponse)(nil), // 5: swap.v1.MsgCreateCashOutIntentResponse
	(*MsgPayoutReceipt)(nil),               // 6: swap.v1.MsgPayoutReceipt
	(*MsgPayoutReceiptResponse)(nil),       // 7: swap.v1.MsgPayoutReceiptResponse
	(*MsgAbortCashOutIntent)(nil),          // 8: swap.v1.MsgAbortCashOutIntent
	(*MsgAbortCashOutIntentResponse)(nil),  // 9: swap.v1.MsgAbortCashOutIntentResponse
	(*DepositVoucher)(nil),                 // 10: swap.v1.DepositVoucher
	(*CashOutIntent)(nil),                  // 11: swap.v1.CashOutIntent
	(*PayoutReceipt)(nil),                  // 12: swap.v1.PayoutReceipt
}
var file_swap_v1_tx_proto_depIdxs = []int32{
	10, // 0: swap.v1.MsgMintDepositVoucher.voucher:type_name -> swap.v1.DepositVoucher
	11, // 1: swap.v1.MsgCreateCashOutIntent.intent:type_name -> swap.v1.CashOutIntent
	12, // 2: swap.v1.MsgPayoutReceipt.receipt:type_name -> swap.v1.PayoutReceipt
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_swap_v1_tx_proto_init() }
func file_swap_v1_tx_proto_init() {
	if File_swap_v1_tx_proto != nil {
		return
	}
	file_swap_v1_stable_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_swap_v1_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSwapExactIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSwapExactOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMintDepositVoucher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMintDepositVoucherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateCashOutIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateCashOutIntentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPayoutReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPayoutReceiptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAbortCashOutIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_tx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAbortCashOutIntentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_swap_v1_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swap_v1_tx_proto_goTypes,
		DependencyIndexes: file_swap_v1_tx_proto_depIdxs,
		MessageInfos:      file_swap_v1_tx_proto_msgTypes,
	}.Build()
	File_swap_v1_tx_proto = out.File
	file_swap_v1_tx_proto_rawDesc = nil
	file_swap_v1_tx_proto_goTypes = nil
	file_swap_v1_tx_proto_depIdxs = nil
}
