replicaCount: 1

image:
  repository: ghcr.io/nhbchain/lendingd
  tag: ""
  pullPolicy: IfNotPresent

env:
  - name: NHB_ENV
    value: staging

service:
  type: ClusterIP
  port: 50053

config:
  enabled: true
  path: /etc/nhb/lendingd.yaml
  content: |
    listen: ":50053"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
