version: '3.9'

services:
  tempo:
    image: grafana/tempo:2.4.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200:3200"
      - "4318:4318"

  loki:
    image: grafana/loki:2.9.4
    command: ["-config.file=/etc/loki/config.yaml"]
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml:ro
    ports:
      - "3100:3100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0
    command: ["--config=/etc/otelcol/collector.yaml"]
    volumes:
      - ../../ops/otel/collector.yaml:/etc/otelcol/collector.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
      - "13133:13133"
    depends_on:
      - tempo
      - loki

  prometheus:
    image: prom/prometheus:v2.49.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ../../ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../../ops/prometheus/rules:/etc/prometheus/rules:ro
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:10.4.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../../ops/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki

volumes: {}
