// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: lending/v1/lending.proto

package lendingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketKey) Reset() {
	*x = MarketKey{}
	mi := &file_lending_v1_lending_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketKey) ProtoMessage() {}

func (x *MarketKey) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketKey.ProtoReflect.Descriptor instead.
func (*MarketKey) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{0}
}

func (x *MarketKey) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Market struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              *MarketKey             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	BaseAsset        string                 `protobuf:"bytes,2,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	CollateralFactor string                 `protobuf:"bytes,3,opt,name=collateral_factor,json=collateralFactor,proto3" json:"collateral_factor,omitempty"`
	ReserveFactor    string                 `protobuf:"bytes,4,opt,name=reserve_factor,json=reserveFactor,proto3" json:"reserve_factor,omitempty"`
	LiquidityIndex   string                 `protobuf:"bytes,5,opt,name=liquidity_index,json=liquidityIndex,proto3" json:"liquidity_index,omitempty"`
	BorrowIndex      string                 `protobuf:"bytes,6,opt,name=borrow_index,json=borrowIndex,proto3" json:"borrow_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_lending_v1_lending_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{1}
}

func (x *Market) GetKey() *MarketKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Market) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *Market) GetCollateralFactor() string {
	if x != nil {
		return x.CollateralFactor
	}
	return ""
}

func (x *Market) GetReserveFactor() string {
	if x != nil {
		return x.ReserveFactor
	}
	return ""
}

func (x *Market) GetLiquidityIndex() string {
	if x != nil {
		return x.LiquidityIndex
	}
	return ""
}

func (x *Market) GetBorrowIndex() string {
	if x != nil {
		return x.BorrowIndex
	}
	return ""
}

type AccountPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Supplied      string                 `protobuf:"bytes,2,opt,name=supplied,proto3" json:"supplied,omitempty"`
	Borrowed      string                 `protobuf:"bytes,3,opt,name=borrowed,proto3" json:"borrowed,omitempty"`
	Collateral    string                 `protobuf:"bytes,4,opt,name=collateral,proto3" json:"collateral,omitempty"`
	HealthFactor  string                 `protobuf:"bytes,5,opt,name=health_factor,json=healthFactor,proto3" json:"health_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountPosition) Reset() {
	*x = AccountPosition{}
	mi := &file_lending_v1_lending_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPosition) ProtoMessage() {}

func (x *AccountPosition) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPosition.ProtoReflect.Descriptor instead.
func (*AccountPosition) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{2}
}

func (x *AccountPosition) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountPosition) GetSupplied() string {
	if x != nil {
		return x.Supplied
	}
	return ""
}

func (x *AccountPosition) GetBorrowed() string {
	if x != nil {
		return x.Borrowed
	}
	return ""
}

func (x *AccountPosition) GetCollateral() string {
	if x != nil {
		return x.Collateral
	}
	return ""
}

func (x *AccountPosition) GetHealthFactor() string {
	if x != nil {
		return x.HealthFactor
	}
	return ""
}

type GetMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *MarketKey             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketRequest) Reset() {
	*x = GetMarketRequest{}
	mi := &file_lending_v1_lending_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketRequest) ProtoMessage() {}

func (x *GetMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketRequest.ProtoReflect.Descriptor instead.
func (*GetMarketRequest) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{3}
}

func (x *GetMarketRequest) GetKey() *MarketKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *Market                `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketResponse) Reset() {
	*x = GetMarketResponse{}
	mi := &file_lending_v1_lending_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketResponse) ProtoMessage() {}

func (x *GetMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketResponse.ProtoReflect.Descriptor instead.
func (*GetMarketResponse) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{4}
}

func (x *GetMarketResponse) GetMarket() *Market {
	if x != nil {
		return x.Market
	}
	return nil
}

type ListMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsRequest) Reset() {
	*x = ListMarketsRequest{}
	mi := &file_lending_v1_lending_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsRequest) ProtoMessage() {}

func (x *ListMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsRequest.ProtoReflect.Descriptor instead.
func (*ListMarketsRequest) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{5}
}

type ListMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsResponse) Reset() {
	*x = ListMarketsResponse{}
	mi := &file_lending_v1_lending_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsResponse) ProtoMessage() {}

func (x *ListMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsResponse.ProtoReflect.Descriptor instead.
func (*ListMarketsResponse) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{6}
}

func (x *ListMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_lending_v1_lending_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{7}
}

func (x *GetPositionRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type GetPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *AccountPosition       `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionResponse) Reset() {
	*x = GetPositionResponse{}
	mi := &file_lending_v1_lending_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionResponse) ProtoMessage() {}

func (x *GetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionResponse.ProtoReflect.Descriptor instead.
func (*GetPositionResponse) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{8}
}

func (x *GetPositionResponse) GetPosition() *AccountPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type SupplyAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Market        *MarketKey             `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyAssetRequest) Reset() {
	*x = SupplyAssetRequest{}
	mi := &file_lending_v1_lending_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyAssetRequest) ProtoMessage() {}

func (x *SupplyAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyAssetRequest.ProtoReflect.Descriptor instead.
func (*SupplyAssetRequest) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{9}
}

func (x *SupplyAssetRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SupplyAssetRequest) GetMarket() *MarketKey {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *SupplyAssetRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type SupplyAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *AccountPosition       `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyAssetResponse) Reset() {
	*x = SupplyAssetResponse{}
	mi := &file_lending_v1_lending_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyAssetResponse) ProtoMessage() {}

func (x *SupplyAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyAssetResponse.ProtoReflect.Descriptor instead.
func (*SupplyAssetResponse) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{10}
}

func (x *SupplyAssetResponse) GetPosition() *AccountPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type WithdrawAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Market        *MarketKey             `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawAssetRequest) Reset() {
	*x = WithdrawAssetRequest{}
	mi := &file_lending_v1_lending_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawAssetRequest) ProtoMessage() {}

func (x *WithdrawAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawAssetRequest.ProtoReflect.Descriptor instead.
func (*WithdrawAssetRequest) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{11}
}

func (x *WithdrawAssetRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *WithdrawAssetRequest) GetMarket() *MarketKey {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *WithdrawAssetRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type WithdrawAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *AccountPosition       `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawAssetResponse) Reset() {
	*x = WithdrawAssetResponse{}
	mi := &file_lending_v1_lending_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawAssetResponse) ProtoMessage() {}

func (x *WithdrawAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawAssetResponse.ProtoReflect.Descriptor instead.
func (*WithdrawAssetResponse) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{12}
}

func (x *WithdrawAssetResponse) GetPosition() *AccountPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type BorrowAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Market        *MarketKey             `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowAssetRequest) Reset() {
	*x = BorrowAssetRequest{}
	mi := &file_lending_v1_lending_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowAssetRequest) ProtoMessage() {}

func (x *BorrowAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowAssetRequest.ProtoReflect.Descriptor instead.
func (*BorrowAssetRequest) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{13}
}

func (x *BorrowAssetRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BorrowAssetRequest) GetMarket() *MarketKey {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *BorrowAssetRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type BorrowAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *AccountPosition       `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowAssetResponse) Reset() {
	*x = BorrowAssetResponse{}
	mi := &file_lending_v1_lending_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowAssetResponse) ProtoMessage() {}

func (x *BorrowAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowAssetResponse.ProtoReflect.Descriptor instead.
func (*BorrowAssetResponse) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{14}
}

func (x *BorrowAssetResponse) GetPosition() *AccountPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type RepayAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Market        *MarketKey             `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepayAssetRequest) Reset() {
	*x = RepayAssetRequest{}
	mi := &file_lending_v1_lending_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepayAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepayAssetRequest) ProtoMessage() {}

func (x *RepayAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepayAssetRequest.ProtoReflect.Descriptor instead.
func (*RepayAssetRequest) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{15}
}

func (x *RepayAssetRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RepayAssetRequest) GetMarket() *MarketKey {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *RepayAssetRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type RepayAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *AccountPosition       `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepayAssetResponse) Reset() {
	*x = RepayAssetResponse{}
	mi := &file_lending_v1_lending_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepayAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepayAssetResponse) ProtoMessage() {}

func (x *RepayAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_v1_lending_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepayAssetResponse.ProtoReflect.Descriptor instead.
func (*RepayAssetResponse) Descriptor() ([]byte, []int) {
	return file_lending_v1_lending_proto_rawDescGZIP(), []int{16}
}

func (x *RepayAssetResponse) GetPosition() *AccountPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_lending_v1_lending_proto protoreflect.FileDescriptor

const file_lending_v1_lending_proto_rawDesc = "" +
	"\n" +
	"\x18lending/v1/lending.proto\x12\n" +
	"lending.v1\"#\n" +
	"\tMarketKey\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xf0\x01\n" +
	"\x06Market\x12'\n" +
	"\x03key\x18\x01 \x01(\v2\x15.lending.v1.MarketKeyR\x03key\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x02 \x01(\tR\tbaseAsset\x12+\n" +
	"\x11collateral_factor\x18\x03 \x01(\tR\x10collateralFactor\x12%\n" +
	"\x0ereserve_factor\x18\x04 \x01(\tR\rreserveFactor\x12'\n" +
	"\x0fliquidity_index\x18\x05 \x01(\tR\x0eliquidityIndex\x12!\n" +
	"\fborrow_index\x18\x06 \x01(\tR\vborrowIndex\"\xa8\x01\n" +
	"\x0fAccountPosition\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bsupplied\x18\x02 \x01(\tR\bsupplied\x12\x1a\n" +
	"\bborrowed\x18\x03 \x01(\tR\bborrowed\x12\x1e\n" +
	"\n" +
	"collateral\x18\x04 \x01(\tR\n" +
	"collateral\x12#\n" +
	"\rhealth_factor\x18\x05 \x01(\tR\fhealthFactor\";\n" +
	"\x10GetMarketRequest\x12'\n" +
	"\x03key\x18\x01 \x01(\v2\x15.lending.v1.MarketKeyR\x03key\"?\n" +
	"\x11GetMarketResponse\x12*\n" +
	"\x06market\x18\x01 \x01(\v2\x12.lending.v1.MarketR\x06market\"\x14\n" +
	"\x12ListMarketsRequest\"C\n" +
	"\x13ListMarketsResponse\x12,\n" +
	"\amarkets\x18\x01 \x03(\v2\x12.lending.v1.MarketR\amarkets\".\n" +
	"\x12GetPositionRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"N\n" +
	"\x13GetPositionResponse\x127\n" +
	"\bposition\x18\x01 \x01(\v2\x1b.lending.v1.AccountPositionR\bposition\"u\n" +
	"\x12SupplyAssetRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12-\n" +
	"\x06market\x18\x02 \x01(\v2\x15.lending.v1.MarketKeyR\x06market\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"N\n" +
	"\x13SupplyAssetResponse\x127\n" +
	"\bposition\x18\x01 \x01(\v2\x1b.lending.v1.AccountPositionR\bposition\"w\n" +
	"\x14WithdrawAssetRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12-\n" +
	"\x06market\x18\x02 \x01(\v2\x15.lending.v1.MarketKeyR\x06market\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"P\n" +
	"\x15WithdrawAssetResponse\x127\n" +
	"\bposition\x18\x01 \x01(\v2\x1b.lending.v1.AccountPositionR\bposition\"u\n" +
	"\x12BorrowAssetRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12-\n" +
	"\x06market\x18\x02 \x01(\v2\x15.lending.v1.MarketKeyR\x06market\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"N\n" +
	"\x13BorrowAssetResponse\x127\n" +
	"\bposition\x18\x01 \x01(\v2\x1b.lending.v1.AccountPositionR\bposition\"t\n" +
	"\x11RepayAssetRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12-\n" +
	"\x06market\x18\x02 \x01(\v2\x15.lending.v1.MarketKeyR\x06market\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"M\n" +
	"\x12RepayAssetResponse\x127\n" +
	"\bposition\x18\x01 \x01(\v2\x1b.lending.v1.AccountPositionR\bposition2\xbd\x04\n" +
	"\x0eLendingService\x12H\n" +
	"\tGetMarket\x12\x1c.lending.v1.GetMarketRequest\x1a\x1d.lending.v1.GetMarketResponse\x12N\n" +
	"\vListMarkets\x12\x1e.lending.v1.ListMarketsRequest\x1a\x1f.lending.v1.ListMarketsResponse\x12N\n" +
	"\vGetPosition\x12\x1e.lending.v1.GetPositionRequest\x1a\x1f.lending.v1.GetPositionResponse\x12N\n" +
	"\vSupplyAsset\x12\x1e.lending.v1.SupplyAssetRequest\x1a\x1f.lending.v1.SupplyAssetResponse\x12T\n" +
	"\rWithdrawAsset\x12 .lending.v1.WithdrawAssetRequest\x1a!.lending.v1.WithdrawAssetResponse\x12N\n" +
	"\vBorrowAsset\x12\x1e.lending.v1.BorrowAssetRequest\x1a\x1f.lending.v1.BorrowAssetResponse\x12K\n" +
	"\n" +
	"RepayAsset\x12\x1d.lending.v1.RepayAssetRequest\x1a\x1e.lending.v1.RepayAssetResponseB%Z#nhbchain/proto/lending/v1;lendingv1b\x06proto3"

var (
	file_lending_v1_lending_proto_rawDescOnce sync.Once
	file_lending_v1_lending_proto_rawDescData []byte
)

func file_lending_v1_lending_proto_rawDescGZIP() []byte {
	file_lending_v1_lending_proto_rawDescOnce.Do(func() {
		file_lending_v1_lending_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lending_v1_lending_proto_rawDesc), len(file_lending_v1_lending_proto_rawDesc)))
	})
	return file_lending_v1_lending_proto_rawDescData
}

var file_lending_v1_lending_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_lending_v1_lending_proto_goTypes = []any{
	(*MarketKey)(nil),             // 0: lending.v1.MarketKey
	(*Market)(nil),                // 1: lending.v1.Market
	(*AccountPosition)(nil),       // 2: lending.v1.AccountPosition
	(*GetMarketRequest)(nil),      // 3: lending.v1.GetMarketRequest
	(*GetMarketResponse)(nil),     // 4: lending.v1.GetMarketResponse
	(*ListMarketsRequest)(nil),    // 5: lending.v1.ListMarketsRequest
	(*ListMarketsResponse)(nil),   // 6: lending.v1.ListMarketsResponse
	(*GetPositionRequest)(nil),    // 7: lending.v1.GetPositionRequest
	(*GetPositionResponse)(nil),   // 8: lending.v1.GetPositionResponse
	(*SupplyAssetRequest)(nil),    // 9: lending.v1.SupplyAssetRequest
	(*SupplyAssetResponse)(nil),   // 10: lending.v1.SupplyAssetResponse
	(*WithdrawAssetRequest)(nil),  // 11: lending.v1.WithdrawAssetRequest
	(*WithdrawAssetResponse)(nil), // 12: lending.v1.WithdrawAssetResponse
	(*BorrowAssetRequest)(nil),    // 13: lending.v1.BorrowAssetRequest
	(*BorrowAssetResponse)(nil),   // 14: lending.v1.BorrowAssetResponse
	(*RepayAssetRequest)(nil),     // 15: lending.v1.RepayAssetRequest
	(*RepayAssetResponse)(nil),    // 16: lending.v1.RepayAssetResponse
}
var file_lending_v1_lending_proto_depIdxs = []int32{
	0,  // 0: lending.v1.Market.key:type_name -> lending.v1.MarketKey
	0,  // 1: lending.v1.GetMarketRequest.key:type_name -> lending.v1.MarketKey
	1,  // 2: lending.v1.GetMarketResponse.market:type_name -> lending.v1.Market
	1,  // 3: lending.v1.ListMarketsResponse.markets:type_name -> lending.v1.Market
	2,  // 4: lending.v1.GetPositionResponse.position:type_name -> lending.v1.AccountPosition
	0,  // 5: lending.v1.SupplyAssetRequest.market:type_name -> lending.v1.MarketKey
	2,  // 6: lending.v1.SupplyAssetResponse.position:type_name -> lending.v1.AccountPosition
	0,  // 7: lending.v1.WithdrawAssetRequest.market:type_name -> lending.v1.MarketKey
	2,  // 8: lending.v1.WithdrawAssetResponse.position:type_name -> lending.v1.AccountPosition
	0,  // 9: lending.v1.BorrowAssetRequest.market:type_name -> lending.v1.MarketKey
	2,  // 10: lending.v1.BorrowAssetResponse.position:type_name -> lending.v1.AccountPosition
	0,  // 11: lending.v1.RepayAssetRequest.market:type_name -> lending.v1.MarketKey
	2,  // 12: lending.v1.RepayAssetResponse.position:type_name -> lending.v1.AccountPosition
	3,  // 13: lending.v1.LendingService.GetMarket:input_type -> lending.v1.GetMarketRequest
	5,  // 14: lending.v1.LendingService.ListMarkets:input_type -> lending.v1.ListMarketsRequest
	7,  // 15: lending.v1.LendingService.GetPosition:input_type -> lending.v1.GetPositionRequest
	9,  // 16: lending.v1.LendingService.SupplyAsset:input_type -> lending.v1.SupplyAssetRequest
	11, // 17: lending.v1.LendingService.WithdrawAsset:input_type -> lending.v1.WithdrawAssetRequest
	13, // 18: lending.v1.LendingService.BorrowAsset:input_type -> lending.v1.BorrowAssetRequest
	15, // 19: lending.v1.LendingService.RepayAsset:input_type -> lending.v1.RepayAssetRequest
	4,  // 20: lending.v1.LendingService.GetMarket:output_type -> lending.v1.GetMarketResponse
	6,  // 21: lending.v1.LendingService.ListMarkets:output_type -> lending.v1.ListMarketsResponse
	8,  // 22: lending.v1.LendingService.GetPosition:output_type -> lending.v1.GetPositionResponse
	10, // 23: lending.v1.LendingService.SupplyAsset:output_type -> lending.v1.SupplyAssetResponse
	12, // 24: lending.v1.LendingService.WithdrawAsset:output_type -> lending.v1.WithdrawAssetResponse
	14, // 25: lending.v1.LendingService.BorrowAsset:output_type -> lending.v1.BorrowAssetResponse
	16, // 26: lending.v1.LendingService.RepayAsset:output_type -> lending.v1.RepayAssetResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_lending_v1_lending_proto_init() }
func file_lending_v1_lending_proto_init() {
	if File_lending_v1_lending_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lending_v1_lending_proto_rawDesc), len(file_lending_v1_lending_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lending_v1_lending_proto_goTypes,
		DependencyIndexes: file_lending_v1_lending_proto_depIdxs,
		MessageInfos:      file_lending_v1_lending_proto_msgTypes,
	}.Build()
	File_lending_v1_lending_proto = out.File
	file_lending_v1_lending_proto_goTypes = nil
	file_lending_v1_lending_proto_depIdxs = nil
}
