ListenAddress = "0.0.0.0:6002"
RPCAddress = "0.0.0.0:8081"
DataDir = "/var/lib/nhb/consensus"
GenesisFile = ""
AllowAutogenesis = true
NetworkName = "nhb-mininet"

[mempool]
MaxTransactions = 5000

[p2p]
NetworkId = 187001
MaxPeers = 32
MaxInbound = 24
MaxOutbound = 16
MinPeers = 8
OutboundPeers = 8
Bootnodes = []
PersistentPeers = []
Seeds = []
BanScore = 100
GreyScore = 50
RateMsgsPerSec = 50
Burst = 200
HandshakeTimeoutMs = 3000
PingIntervalSeconds = 30
PingTimeoutSeconds = 90
BanDurationSeconds = 3600
DialBackoffSeconds = 30
PEX = true
