// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: consensus/v1/tx.proto

package consensusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Payer         string                 `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_consensus_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_consensus_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Fee) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Fee) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Fee) GetPayer() string {
	if x != nil {
		return x.Payer
	}
	return ""
}

type TxEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *anypb.Any             `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ChainId       string                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Fee           *Fee                   `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Memo          string                 `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	IntentRef     []byte                 `protobuf:"bytes,6,opt,name=intent_ref,json=intentRef,proto3" json:"intent_ref,omitempty"`
	IntentExpiry  uint64                 `protobuf:"varint,7,opt,name=intent_expiry,json=intentExpiry,proto3" json:"intent_expiry,omitempty"`
	MerchantAddr  string                 `protobuf:"bytes,8,opt,name=merchant_addr,json=merchantAddr,proto3" json:"merchant_addr,omitempty"`
	DeviceId      string                 `protobuf:"bytes,9,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RefundOf      string                 `protobuf:"bytes,10,opt,name=refund_of,json=refundOf,proto3" json:"refund_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxEnvelope) Reset() {
	*x = TxEnvelope{}
	mi := &file_consensus_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxEnvelope) ProtoMessage() {}

func (x *TxEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxEnvelope.ProtoReflect.Descriptor instead.
func (*TxEnvelope) Descriptor() ([]byte, []int) {
	return file_consensus_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxEnvelope) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TxEnvelope) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TxEnvelope) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *TxEnvelope) GetFee() *Fee {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *TxEnvelope) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *TxEnvelope) GetIntentRef() []byte {
	if x != nil {
		return x.IntentRef
	}
	return nil
}

func (x *TxEnvelope) GetIntentExpiry() uint64 {
	if x != nil {
		return x.IntentExpiry
	}
	return 0
}

func (x *TxEnvelope) GetMerchantAddr() string {
	if x != nil {
		return x.MerchantAddr
	}
	return ""
}

func (x *TxEnvelope) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TxEnvelope) GetRefundOf() string {
	if x != nil {
		return x.RefundOf
	}
	return ""
}

type TxSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSignature) Reset() {
	*x = TxSignature{}
	mi := &file_consensus_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSignature) ProtoMessage() {}

func (x *TxSignature) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSignature.ProtoReflect.Descriptor instead.
func (*TxSignature) Descriptor() ([]byte, []int) {
	return file_consensus_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *TxSignature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *TxSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SignedTxEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *TxEnvelope            `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Signature     *TxSignature           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTxEnvelope) Reset() {
	*x = SignedTxEnvelope{}
	mi := &file_consensus_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTxEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTxEnvelope) ProtoMessage() {}

func (x *SignedTxEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTxEnvelope.ProtoReflect.Descriptor instead.
func (*SignedTxEnvelope) Descriptor() ([]byte, []int) {
	return file_consensus_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *SignedTxEnvelope) GetEnvelope() *TxEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SignedTxEnvelope) GetSignature() *TxSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SubmitTxEnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *SignedTxEnvelope      `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxEnvelopeRequest) Reset() {
	*x = SubmitTxEnvelopeRequest{}
	mi := &file_consensus_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxEnvelopeRequest) ProtoMessage() {}

func (x *SubmitTxEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*SubmitTxEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_consensus_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitTxEnvelopeRequest) GetTx() *SignedTxEnvelope {
	if x != nil {
		return x.Tx
	}
	return nil
}

type SubmitTxEnvelopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxEnvelopeResponse) Reset() {
	*x = SubmitTxEnvelopeResponse{}
	mi := &file_consensus_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxEnvelopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxEnvelopeResponse) ProtoMessage() {}

func (x *SubmitTxEnvelopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxEnvelopeResponse.ProtoReflect.Descriptor instead.
func (*SubmitTxEnvelopeResponse) Descriptor() ([]byte, []int) {
	return file_consensus_v1_tx_proto_rawDescGZIP(), []int{5}
}

var File_consensus_v1_tx_proto protoreflect.FileDescriptor

const file_consensus_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x15consensus/v1/tx.proto\x12\fconsensus.v1\x1a\x19google/protobuf/any.proto\"I\n" +
	"\x03Fee\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\x12\x14\n" +
	"\x05payer\x18\x03 \x01(\tR\x05payer\"\xc9\x02\n" +
	"\n" +
	"TxEnvelope\x12.\n" +
	"\apayload\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\x12#\n" +
	"\x03fee\x18\x04 \x01(\v2\x11.consensus.v1.FeeR\x03fee\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"intent_ref\x18\x06 \x01(\fR\tintentRef\x12#\n" +
	"\rintent_expiry\x18\a \x01(\x04R\fintentExpiry\x12#\n" +
	"\rmerchant_addr\x18\b \x01(\tR\fmerchantAddr\x12\x1b\n" +
	"\tdevice_id\x18\t \x01(\tR\bdeviceId\x12\x1b\n" +
	"\trefund_of\x18\n" +
	" \x01(\tR\brefundOf\"J\n" +
	"\vTxSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x81\x01\n" +
	"\x10SignedTxEnvelope\x124\n" +
	"\benvelope\x18\x01 \x01(\v2\x18.consensus.v1.TxEnvelopeR\benvelope\x127\n" +
	"\tsignature\x18\x02 \x01(\v2\x19.consensus.v1.TxSignatureR\tsignature\"I\n" +
	"\x17SubmitTxEnvelopeRequest\x12.\n" +
	"\x02tx\x18\x01 \x01(\v2\x1e.consensus.v1.SignedTxEnvelopeR\x02tx\"\x1a\n" +
	"\x18SubmitTxEnvelopeResponseB)Z'nhbchain/proto/consensus/v1;consensusv1b\x06proto3"

var (
	file_consensus_v1_tx_proto_rawDescOnce sync.Once
	file_consensus_v1_tx_proto_rawDescData []byte
)

func file_consensus_v1_tx_proto_rawDescGZIP() []byte {
	file_consensus_v1_tx_proto_rawDescOnce.Do(func() {
		file_consensus_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_v1_tx_proto_rawDesc), len(file_consensus_v1_tx_proto_rawDesc)))
	})
	return file_consensus_v1_tx_proto_rawDescData
}

var file_consensus_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_consensus_v1_tx_proto_goTypes = []any{
	(*Fee)(nil),                      // 0: consensus.v1.Fee
	(*TxEnvelope)(nil),               // 1: consensus.v1.TxEnvelope
	(*TxSignature)(nil),              // 2: consensus.v1.TxSignature
	(*SignedTxEnvelope)(nil),         // 3: consensus.v1.SignedTxEnvelope
	(*SubmitTxEnvelopeRequest)(nil),  // 4: consensus.v1.SubmitTxEnvelopeRequest
	(*SubmitTxEnvelopeResponse)(nil), // 5: consensus.v1.SubmitTxEnvelopeResponse
	(*anypb.Any)(nil),                // 6: google.protobuf.Any
}
var file_consensus_v1_tx_proto_depIdxs = []int32{
	6, // 0: consensus.v1.TxEnvelope.payload:type_name -> google.protobuf.Any
	0, // 1: consensus.v1.TxEnvelope.fee:type_name -> consensus.v1.Fee
	1, // 2: consensus.v1.SignedTxEnvelope.envelope:type_name -> consensus.v1.TxEnvelope
	2, // 3: consensus.v1.SignedTxEnvelope.signature:type_name -> consensus.v1.TxSignature
	3, // 4: consensus.v1.SubmitTxEnvelopeRequest.tx:type_name -> consensus.v1.SignedTxEnvelope
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_consensus_v1_tx_proto_init() }
func file_consensus_v1_tx_proto_init() {
	if File_consensus_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_v1_tx_proto_rawDesc), len(file_consensus_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_v1_tx_proto_goTypes,
		DependencyIndexes: file_consensus_v1_tx_proto_depIdxs,
		MessageInfos:      file_consensus_v1_tx_proto_msgTypes,
	}.Build()
	File_consensus_v1_tx_proto = out.File
	file_consensus_v1_tx_proto_goTypes = nil
	file_consensus_v1_tx_proto_depIdxs = nil
}
