listen: ":7074"
database: "/var/data/swapd.sqlite"
oracle:
  interval: "30s"
  max_age: "2m"
  min_feeds: 2
sources:
  - name: now
    type: nowpayments
    endpoint: https://api.nowpayments.io/v1/exchange/rates
    api_key: ""
  - name: gecko
    type: coingecko
    endpoint: https://api.coingecko.com/api/v3/simple/price
    assets:
      ZNHB: znhb
pairs:
  - base: ZNHB
    quote: USD
policy:
  id: default
  mint_limit: 10
  redeem_limit: 5
  window: "1h"
stable:
  paused: true
  quote_ttl: "1m"
  max_slippage_bps: 50
  soft_inventory: 1000000
  assets:
    - symbol: ZNHB
      base: ZNHB
      quote: USD
