name: CI
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.22.6']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Set Go flags
        run: echo "GOFLAGS=-buildvcs=false" >> "$GITHUB_ENV"
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -trimpath -ldflags="-s -w" -buildvcs=false -o bin/nhb ./cmd/nhb
      - name: Test
        run: go test ./...
